### PR TITLE
Task/update home page

### PR DESCRIPTION
**Pull request by jtardioli**
- Update landing page with statue + mobile styling
- Fix the Navbar on mobile 
- add a custom theme with custom colours to ChakraProvider

image

image

image

### CODE REVIEW

**Review by GarrettJMU — APPROVED** [review]

**Comment by bigint** [comment]
Deployment failed @GarrettJMU @ctjlewis 🤔

**Comment by ctjlewis** [comment]
I saw. It failed because of some Vercel error claiming there wasn't a commit hash (there is). Did I add you to the Vercel team @bigint?

**Comment by bigint** [comment]
no, i'm not there @ctjlewis

**Comment by ctjlewis** [comment]
Really weird. This was actually just a yarn.lock bug. If you ever have conflicts in yarn.lock, just refresh it from scratch via `rm yarn.lock && yarn`.

**Pull request merged**
